struct ek ekler[]={
"","","","","","","","",
"e","es","e","e","ons","ez","ent","ent",
"ais","ais","ait","ait","ions","iez","aient","aient",
"ai","as","a","a","ons","ez","ont","ont",
"e","es","e","e","ions","iez","ent","ent",
"ai","as","a","a","ƒmes","ƒtes","Šrent","Šrent",
"is","is","it","it","issons","issez","issent","issent",
"issais","issais","issait","issait","issions","issiez","issaient","issaient",
"isse","isses","isse","isse","issions","issiez","issaient","issaient",
"is","is","it","it","Œmes","Œtes","irent","irent",
"vais","vas","va","va","allons","allez","vont","vont",
"s","s","t","t","ons","ez","ent","ent",
"ins","ins","int","int","Œnmes","Œntes","inrent","inrent",
"us","us","ut","ut","–mes","–tes","urent","urent",
"x","x","t","t","ons","ez","ent","ent",
"s","s","d","d","ons","ez","ent","ent",
"suis","es","est","est","sommes","ˆtes","sont","sont",
"ai","as","a","a","avons","avez","ont","ont",
"e","es","t","t","ons","ez","ent","ent",
"‹s","‹s","‹t","‹t","‹mes","‹tes","‹rent","‹rent",
"–s","–s","–t","–t","–mes","–tes","–rent","–rent",
"isse","isses","isse","isse","issions","issiez","issent","issent",
"","","","","","","",""
};


struct aux auxil[]={
"j'ai","tu as","il a","elle a","nous avons","vous avez","ils ont","elles ont",
"je suis","tu es","il est","elle est","nous sommes","vous ˆtes","ils sont","elles sont",
"j'avais","tu avais","il avait","elle avait","nous avions","vous aviez","ils avaient","elles avaient",
"j'‚tais","tu ‚tais","il ‚tait","elle ‚tait","nous ‚tions","vous ‚tiez","ils ‚taient","elles ‚taient",
"j'aurai","tu auras","il aura","elle aura","nous aurons","vous aurez","ils auront","elles auront",
"je serai","tu seras","il sera","elle sera","nous serons","vous serez","ils seront","elles seront",
"que j'aie","que tu aies","qu'il ait","qu'elle ait","que nous ayons","que vous ayez","qu'ils aient","qu'elles aient",
"que je sois","que tu sois","qu'il soit","qu'elle soit","que nous soyons","que vous soyez","qu'ils soient","qu'elles soient",
"j'aurais","tu aurais","il aurait","elle aurait","nous aurions","vous auriez","ils auraient","elles auraient",
"je serais","tu serais","il serait","elle serait","nous serions","vous seriez","ils seraient","elles seraient"
};