void  present( struct tt  *, int, char *, char * );
void  imparfait( struct tt  *, int, char *, char * );
void  fsimple( struct tt  *, int, char *, char * );
void  subpresent( struct tt  *, int, char *, char * );
void  psimple( struct tt  *, int, char *, char * );
void  imperatif( struct tt  *, int, char *, char * );
void  conpresent( struct tt  *, int, char *, char * );

void  tempscomp( int, struct tt  *, int, int, char *, char * );
void  pcompose( struct tt  *, int, int, char *, char * );
void  pparfait( struct tt  *, int, int, char *, char * );
void  fanterieur( struct tt  *, int, int, char *, char * );
void  subpasse( struct tt  *, int, int, char *, char * );
void  conpasse( struct tt  *, int, int, char *, char * );

static void  pronominale( char * );
static void  subpronominale( char * );
static void  impersonnel( char * );

static void  kokbul( int, char *, char * );
void  kesme( char *, char );
static void  birlestir( char *, char *, char *, char *, char * );
static void  duzelt( char * );
void  bosalt( char * );