struct kk{
	int num;
	char fil[15];
	int ek;
} kokler[]={
39,"savoir",6,  0,"avoir",5,  1,"ˆtre",4,  16,"g‚sir",5,  17,"envoyer",9,
19,"ha‹r",4,  20,"taire",5,  21,"aller",5,  25,"vˆtir",5,  27,"cueillir",8,
28,"faillir",7,  29,"bouillir",8,  30,"dormir",6,  31,"courir",6,
32,"mourir",6,  33,"servir",6,  34,"fuir",4,  35,"ou‹r",4,  38,"pourvoir",8,
40,"devoir",6,  41,"pouvoir",7,  106,"‚mouvoir",8,  42,"mouvoir",7,
43,"pleuvoir",8,  44,"falloir",7,  45,"valoir",6,  46,"vouloir",7,
47,"asseoir",7,  49,"surseoir",8,  53,"battre",5,  61,"plaire",6,
109,"renaŒtre",8,  62,"connaŒtre",7,  63,"naŒtre",6,  14,"repaŒtre",8,
64,"paŒtre",6,  66,"croire",6,  67,"boire",5,  106,"enclore",7,  68,"clore",5,
71,"coudre",6,  72,"moudre",6,  73,"suivre",6,  74,"vivre",5,  75,"lire",4,
78,"‚crire",6,  77,"rire",4,  79,"confire",7,  99,"suffire",7, 103,"occlure",7,
104,"maudire",7, 105,"‚mouvoir",8,  107,"d‚croŒtre",9,  110,"prendre",7,
102,"pr‚dire",7,  76,"dire",4,  17,"envoyer",5,  48,"rapi‚cer",6,
54,"mettre",6,  58,"vaincre",7,  59,"traire",6,  60,"faire",5,  80,"cuire",5,

81,"a‚cer",4,  84,"a‚brer",5,  85,"a‚cher",5,  86,"a‚crer",5,  87,"a‚gler",5,
88,"a‚gner",5,  89,"a‚grer",5,  90,"a‚guer",5,  91,"a‚mer",4,  92,"a‚ner",4,
93,"a‚ser",4,  94,"a‚trer",5,  95,"a‚quer",5,  96,"a‚vrer",5,  97,"a‚per",4,
98,"gal‚jer",4,  108,"circoncire",6,  82,"aeper",4,  83,"aevrer",5,
2,"lever",4,  3,"semer",4,  4,"amener",4,  8,"peser",4,  9,"c‚der",4,
10,"jeter",4,  50,"d‚choir",4,  70,"absoudre",8,  69,"conclure",4,
52,"esp‚rer",4,  56,"r‚p‚ter",4,  57,"craindre",6,  55,"peindre",6,
65,"croŒtre",5,  36,"recevoir",5,  26,"couvrir",4,  23,"acqu‚rir",4,
22,"tenir",4,  15,"payer",4,  13,"aissi‚ger",4,  12,"appeler",7,
100,"r‚soudre",6,  101,"reluire",4,  24,"sentir",3,  11,"modeler",4,
6,"placer",3,  7,"manger",3,  37,"voir",5,  51,"rendre",3,  5,"aimer",2,
18,"finir",2,
-1,"***",-1
};
